services:
  conectus.member.fb:
    container_name: conectusDb
    hostname: conectusDb
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "SqlServer2019!"
      ACCEPT_EULA: "Y"
    networks:
      - service_member_network
    restart: always

networks:
  service_member_network:
    driver: bridge
